"""HTML report generation."""
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from cyberguard.constants import APP_NAME, VERSION, Severity

_log = logging.getLogger("cyberguard")

class HTMLReportGenerator:
    """Generates standalone HTML reports with dark theme and inline CSS."""

    STYLE = """
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
               background: #1a1a2e; color: #e0e0e0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { color: #00d4ff; text-align: center; margin: 20px 0; font-size: 28px; }
        h2 { color: #00d4ff; border-bottom: 2px solid #16213e; padding-bottom: 8px;
             margin: 25px 0 15px; font-size: 20px; }
        h3 { color: #e94560; margin: 15px 0 10px; font-size: 16px; }
        .header { background: #16213e; border-radius: 10px; padding: 20px;
                  margin-bottom: 20px; text-align: center; }
        .header .subtitle { color: #888; font-size: 14px; margin-top: 5px; }
        .card { background: #16213e; border-radius: 8px; padding: 15px;
                margin-bottom: 15px; border-left: 4px solid #00d4ff; }
        .card.critical { border-left-color: #ff0040; }
        .card.high { border-left-color: #ff6b35; }
        .card.medium { border-left-color: #ffc107; }
        .card.low { border-left-color: #28a745; }
        .card.pass { border-left-color: #28a745; }
        .card.fail { border-left-color: #ff0040; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th { background: #0f3460; color: #00d4ff; padding: 10px; text-align: left;
             font-size: 13px; }
        td { padding: 8px 10px; border-bottom: 1px solid #1a1a3e; font-size: 13px; }
        tr:hover { background: #1a1a3e; }
        .score-box { display: inline-block; padding: 15px 25px; border-radius: 10px;
                     font-size: 36px; font-weight: bold; text-align: center;
                     margin: 10px; }
        .score-a { background: #28a745; color: white; }
        .score-b { background: #5cb85c; color: white; }
        .score-c { background: #ffc107; color: #333; }
        .score-d { background: #ff6b35; color: white; }
        .score-f { background: #ff0040; color: white; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px;
                 font-size: 11px; font-weight: bold; }
        .badge-critical { background: #ff0040; color: white; }
        .badge-high { background: #ff6b35; color: white; }
        .badge-medium { background: #ffc107; color: #333; }
        .badge-low { background: #28a745; color: white; }
        .badge-pass { background: #28a745; color: white; }
        .badge-fail { background: #ff0040; color: white; }
        .badge-info { background: #00d4ff; color: #333; }
        .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                        gap: 15px; margin: 15px 0; }
        .summary-item { background: #0f3460; border-radius: 8px; padding: 15px;
                        text-align: center; }
        .summary-item .value { font-size: 28px; font-weight: bold; color: #00d4ff; }
        .summary-item .label { font-size: 12px; color: #888; margin-top: 5px; }
        .footer { text-align: center; color: #555; margin-top: 30px; padding: 15px;
                  border-top: 1px solid #16213e; font-size: 12px; }
        .progress-bar { background: #0f3460; border-radius: 5px; height: 20px;
                        overflow: hidden; margin: 5px 0; }
        .progress-fill { height: 100%; border-radius: 5px; transition: width 0.3s; }
        .recommendation { background: #0f3460; border-radius: 6px; padding: 12px;
                          margin: 8px 0; border-left: 3px solid #ffc107; }
    </style>"""

    @classmethod
    def _esc(cls, value: Any) -> str:
        """Escape user-controlled strings to prevent XSS in HTML reports."""
        return html_mod.escape(str(value)) if value else ""

    @classmethod
    def _wrap(cls, title: str, body: str) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        safe_title = cls._esc(title)
        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:;">
<title>{safe_title} - CyberGuard</title>{cls.STYLE}</head>
<body><div class="container">
<div class="header"><h1>🛡️ {safe_title}</h1>
<div class="subtitle">Generated by CyberGuard Professional Security Toolkit v{VERSION} | {ts}</div></div>
{body}
<div class="footer">CyberGuard Professional Security Toolkit v{VERSION} | Report generated {ts}</div>
</div></body></html>"""

    @classmethod
    def _severity_badge(cls, severity: str) -> str:
        s = severity.lower()
        return f'<span class="badge badge-{s}">{severity}</span>'

    @classmethod
    def _score_box(cls, score: float, grade: str) -> str:
        g = grade.lower()
        return f'<div class="score-box score-{g}">{score}/100<br><small>Grade {grade}</small></div>'

    @classmethod
    def _progress_bar(cls, pct: float, color: str = "#00d4ff") -> str:
        return f'<div class="progress-bar"><div class="progress-fill" style="width:{pct}%;background:{color}"></div></div>'

    @classmethod
    def assessment_report(cls, findings: List[dict], scores: dict,
                          title: str = "Security Assessment Report") -> str:
        body = ""
        # Score overview
        body += '<h2>Score Overview</h2><div class="summary-grid">'
        for cat, sc in scores.items():
            body += f'<div class="summary-item"><div class="value">{sc.get("score", 0)}</div>'
            body += f'<div class="label">{cls._esc(cat)} (Grade {cls._esc(sc.get("grade", "N/A"))})</div></div>'
        body += '</div>'

        # Findings
        if findings:
            body += '<h2>Findings</h2>'
            for f in findings:
                sev = f.get("severity", Severity.LOW).lower()
                body += f'<div class="card {html_mod.escape(sev)}">'
                body += f'<h3>{cls._severity_badge(f.get("severity", Severity.LOW))} {cls._esc(f.get("title", ""))}</h3>'
                body += f'<p>{cls._esc(f.get("description", ""))}</p>'
                if f.get("recommendation"):
                    body += f'<div class="recommendation"><strong>Recommendation:</strong> {cls._esc(f["recommendation"])}</div>'
                body += '</div>'

        return cls._wrap(title, body)

    @classmethod
    def compliance_report(cls, results: List[dict], framework: str,
                          score: dict) -> str:
        body = f'<h2>{framework} Compliance</h2>'
        body += cls._score_box(score.get("score", 0), score.get("grade", "N/A"))
        body += f'<p>Passed: {score.get("passed", 0)} / {score.get("total", 0)}</p>'
        body += cls._progress_bar(score.get("score", 0))

        body += '<table><tr><th>ID</th><th>Check</th><th>Status</th><th>Details</th></tr>'
        for r in results:
            status = r.get("status", "FAIL")
            badge = '<span class="badge badge-pass">PASS</span>' if status == "PASS" else '<span class="badge badge-fail">FAIL</span>'
            body += f'<tr><td>{cls._esc(r.get("id", ""))}</td><td>{cls._esc(r.get("title", ""))}</td>'
            body += f'<td>{badge}</td><td>{cls._esc(r.get("details", ""))}</td></tr>'
        body += '</table>'
        return cls._wrap(f"{framework} Compliance Report", body)

    @classmethod
    def hardening_report(cls, categories: Dict[str, List[dict]], overall_score: dict) -> str:
        body = '<h2>Overall Security Score</h2>'
        body += cls._score_box(overall_score.get("score", 0), overall_score.get("grade", "N/A"))

        for cat_name, checks in categories.items():
            passed = sum(1 for c in checks if c.get("status") == "PASS")
            total = len(checks)
            pct = (passed / total * 100) if total else 0
            body += f'<h2>{cls._esc(cat_name)}</h2>'
            body += f'<p>Passed: {passed}/{total} ({pct:.0f}%)</p>'
            body += cls._progress_bar(pct, "#28a745" if pct >= 80 else "#ffc107" if pct >= 60 else "#ff0040")
            body += '<table><tr><th>Check</th><th>Status</th><th>Details</th></tr>'
            for c in checks:
                st = c.get("status", "FAIL")
                badge = '<span class="badge badge-pass">PASS</span>' if st == "PASS" else '<span class="badge badge-fail">FAIL</span>'
                body += f'<tr><td>{cls._esc(c.get("title", ""))}</td><td>{badge}</td><td>{cls._esc(c.get("details", ""))}</td></tr>'
            body += '</table>'

        return cls._wrap("System Hardening Report", body)

    @classmethod
    def vulnerability_report(cls, vulns: List[dict], score: dict) -> str:
        body = '<h2>Vulnerability Summary</h2>'
        body += cls._score_box(score.get("score", 0), score.get("grade", "N/A"))

        counts = {}
        for v in vulns:
            s = v.get("severity", Severity.LOW)
            counts[s] = counts.get(s, 0) + 1
        body += '<div class="summary-grid">'
        for s in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
            body += f'<div class="summary-item"><div class="value">{counts.get(s, 0)}</div>'
            body += f'<div class="label">{s}</div></div>'
        body += '</div>'

        if vulns:
            body += '<h2>Vulnerability Details</h2>'
            body += '<table><tr><th>ID</th><th>Severity</th><th>Description</th><th>Affected</th></tr>'
            for v in vulns:
                body += f'<tr><td>{cls._esc(v.get("id", "N/A"))}</td>'
                body += f'<td>{cls._severity_badge(v.get("severity", Severity.LOW))}</td>'
                body += f'<td>{cls._esc(v.get("description", ""))}</td>'
                body += f'<td>{cls._esc(v.get("affected", ""))}</td></tr>'
            body += '</table>'

        return cls._wrap("Vulnerability Assessment Report", body)

    @classmethod
    def executive_summary(cls, grade: str, score: float, findings_count: int,
                          top_findings: List[dict], recommendations: List[str]) -> str:
        body = '<h2>Security Grade</h2>'
        body += f'<div style="text-align:center">{cls._score_box(score, grade)}</div>'
        body += f'<div class="summary-grid">'
        body += f'<div class="summary-item"><div class="value">{findings_count}</div><div class="label">Total Findings</div></div>'

        crit = sum(1 for f in top_findings if f.get("severity") == Severity.CRITICAL)
        high = sum(1 for f in top_findings if f.get("severity") == Severity.HIGH)
        body += f'<div class="summary-item"><div class="value">{crit}</div><div class="label">Critical</div></div>'
        body += f'<div class="summary-item"><div class="value">{high}</div><div class="label">High</div></div>'
        body += '</div>'

        if top_findings:
            body += '<h2>Top Findings</h2>'
            for f in top_findings[:10]:
                sev = f.get("severity", Severity.LOW).lower()
                body += f'<div class="card {html_mod.escape(sev)}">'
                body += f'{cls._severity_badge(f.get("severity", Severity.LOW))} <strong>{cls._esc(f.get("title", ""))}</strong>'
                body += f'<p>{cls._esc(f.get("description", ""))}</p></div>'

        if recommendations:
            body += '<h2>Key Recommendations</h2>'
            for i, r in enumerate(recommendations[:10], 1):
                body += f'<div class="recommendation">{i}. {cls._esc(r)}</div>'

        return cls._wrap("Executive Security Summary", body)


# ═══════════════════════════════════════════════════════════════════════════
# BASELINE MANAGER
# ═══════════════════════════════════════════════════════════════════════════
